### ISSUE TITLE
proposal to become a maintainer

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.proxysql#45]
#39

In the past I've contributed already many modules, features, bugs and bug-fixes to ansible and  different collections. I'm become also a maintainer for comminuty.aws.

Since I'm familiar with proxysql and use it in production, I would like to answer the request for maintainers and contributors and be available as a maintainer for the proxysql collection.

**Comment by Andersson007** [comment]
Hi @markuman thanks for the great work! I've just sent the invite ("write").
When you have time, please read / revise the following guidelines:
- [Collection maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst)
- [Ansible committer guidelines](https://docs.ansible.com/ansible/devel/community/committer_guidelines.html)

Thank you!
