### ISSUE TITLE
implement missing_required_lib and dropping MySQL-python (Python 2.x only) at the same time?

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.proxysql#47]
I wonder if we should drop the MySQL-python (Python 2.x only) import check and Python 2.x documentation fragments?

https://github.com/ansible-collections/community.proxysql/blob/main/plugins/module_utils/mysql.py#L24

Imho [MySQL-python](https://github.com/farcepest/MySQLdb1) is dead. And PyMySQL supports at least Python 2.7 via distribution packages.

**Comment by Andersson007** [comment]
As far as I know, [mysqlclient](https://pypi.org/project/mysqlclient/) is actively supported by the same team as develop `pymysql` and `mysqlclient` is imported with the `import MySQLdb` statement. What do you think?

**Comment by markuman** [comment]
I'm only familiar with `PyMySQL`, but I can take look at `mysqlclient` also.

---
some notes from #19 

> duplicate integrationtest with different proxysql versions and also with diffrent connector versions
> [would be also nice to test against different connector versions](https://github.com/ansible-collections/community.proxysql/issues/19#issuecomment-883958401)

**Comment by markuman** [comment]
It looks like `mysqlclient` works as a drop-in replacement.  
Running the integrationtests locally pass-

**Comment by Andersson007** [comment]
Yeah, the interface should be compatible with MySQLdb. Thanks for testing!
